version: "3.8"

networks:
    trading_calculator:
        driver: bridge

services:
    trading_calculator:
        build:
            context: .
        container_name: trading_calculator
        tty: true
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./html:/var/www/html
        networks:
            - trading_calculator
